# Generated by Django 4.2.5 on 2023-11-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('MobileNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('EmailID', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=25, null=True)),
                ('position', models.CharField(blank=True, max_length=25, null=True)),
                ('salary', models.BigIntegerField(blank=True, null=True)),
                ('faceImage', models.BinaryField(blank=True, null=True)),
                ('remaining_leave', models.IntegerField(default=0)),
                ('late_days', models.IntegerField(blank=True, null=True)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('AttendanceID', models.AutoField(primary_key=True, serialize=False)),
                ('Start_Time', models.DateTimeField(blank=True, null=True)),
                ('End_Time', models.DateTimeField(blank=True, null=True)),
                ('leave_start', models.DateTimeField(blank=True, null=True)),
                ('leave_end', models.DateTimeField(blank=True, null=True)),
                ('islate', models.BooleanField(blank=True, null=True)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee')),
            ],
        ),
    ]
